import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Wood-Steel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='p-5'>
        <div>
          <h1>Sofas</h1>
          <div className='py-4'>
            <div className='w-64'>
              <div className='bg-blue-200 p-5 rounded-xl'>
                <Image src='/sofa.png' width={300} height={300} alt=""/>
              </div>
              <div className='mt-2'>
                <h3 className='font-bold text-lg'>Blue Sofa</h3>
                <p className='text-sm mt-2 leading-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas fermentum a purus a porttitor.</p>
                <div className='flex mt-3'>
                  <div className='text-2xl font-bold grow'>&#8377; 8999</div>
                  <button className='bg-emerald-400 text-white py-1 px-3 rounded-xl'>
                    Add to Cart

                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
